### PR TITLE
add multiarch support

### PR DESCRIPTION
**Pull request by seth-priya**
In support of  https://github.com/subchen/frep/issues/27

### CODE REVIEW

**Comment by seth-priya** [comment]
any thoughts on this?

**Comment by FlipSky** [comment]
Support this PR - would love to use this utility on Alpine Linux on Intel and ARM to generate deploy scripts and other things.

**Comment by saghul** [comment]
Was about to open a new issue for suggesting releasing ARM binaries and found this one. 👍

**Comment by subchen** [comment]
Yes, arm binaries is good to release

**Comment by subchen** [comment]
for arch, x86_64 ==> amd64

**Comment by seth-priya** [comment]
thanks @subchen so looks like we will need to explicitly set that as "uname" returns x86_64, causing the travis build to fail? I can fix and test that (sorry about it)

BTW I have tested this and we need it on ppc64le , can we have binaries for that as well, I can work on enabling travis support if that helps

**Comment by seth-priya** [comment]
Fixed in https://github.com/subchen/frep/pull/32

**Comment by subchen** [comment]
yes, welcome for PRs to have ppc64le

**Comment by saghul** [comment]
Nice to see this land! Any chance a new release can be made so the new architectures are provided? :-)

**Pull request merged**
